### ISSUE TITLE
trigger event without input field

### ISSUE THREAD

**Issue by fnumatic** [domino-clj/domino#6]
I would like to trigger events in the way that no input field is needed.
Right now the following works:
```
{:id :add-current
 :inputs  [:current]
 :outputs [:lines]
 :handler (fn [_  {:keys [current]}  {:keys [lines]}]

		  {:lines   (conj lines current)
		   :current {}})}

(domino.core/trigger-events ctx [:add-current])
```
Downside is, that every change in [:current] triggers this event too.

So my preferred way would be like:

```
{:id :add-current
 :inputs  []
 :outputs [:lines :current]
 :handler (fn [_  _  {:keys [lines current]}]

		  {:lines   (conj lines current)
		   :current {}})}

(domino.core/trigger-events ctx [:add-current])
```

Currently this does not work.

Corresponding testcase in domino.core-test would be
```
(deftest trigger-events-without-input
  (let [ctx (core/initialize {:model  [[:n {:id :n}]
                                       [:m {:id :m}]]
                              :events [{:id      :match-n
                                        :inputs  []
                                        :outputs [:m :n]
                                        :handler (fn [_ _ {:keys [n]}]
                                                     {:m n})}]}
                               {:n 10 :m 0})]
    (is (= {:n 10 :m 10} (:domino.core/db (core/trigger-events ctx [:match-n]))))))
```

**Comment by yogthos** [comment]
I definitely agree this would be useful as this allows for events to be used as entry points into the engine. It might be better to treat this as an effect though since generating the data within the event can be seen as an effectful operation.

Current effects only deal with outgoing data, but perhaps we could add an effect type that has outputs instead of inputs, e.g:

```clojure
{:effects
 [{:id :add-current
   :outputs [:lines :current]
   :handler (fn [_  _  {:keys [lines current]}]
		    {:lines   (conj lines current)
		     :current {}})}]
  ...}
```

The implementation for this would be pretty straight forward as you could run these effects to produce the outputs, and then just treat those as regular inputs to `transact`. If you'd be up for doing a PR for this that would be very welcome. :)
